MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet'
        PRETRAINED: True
        OUT_CHANNELS: [ 512, 1024, 2048, 256, 128, 128]
        INPUT_CHANNELS: 3
        
    PRIORS:        
        FEATURE_MAPS: [[90, 51], [45, 26], [23, 13], [12, 7], [6, 4], [4, 2]]

        # See @363
        STRIDES: [[8, 8], [16, 16], [32, 31], [60, 57], [120, 101], [240, 405]]

        # See @367
        MIN_SIZES: [[24, 13], [72, 40], [142, 80], [387, 217], [510, 286], [631, 355]]
        MAX_SIZES: [[72, 40], [142, 80], [387, 217], [510, 286], [631, 355], [754, 424]]
        # BOXES_PER_LOCATION: [6, 4, 4, 6, 4, 4]
INPUT:
    IMAGE_SIZE: [720, 405]
    PIXEL_MEAN: [0.485, 0.456, 0.406]
    PIXEL_STD: [0.229, 0.224, 0.225]
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/tdt_4265_50'
DATASET_DIR: "ssd/data/datasets"
EVAL_STEP: 6000
MODEL_SAVE_STEP: 2000